### ISSUE TITLE
Ensure all ethereum interactions pass a prefixed `0x` in their identifiers

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/dvote-solidity#16]
We already removed the requirement of this prefixed `0x` in our gateways and other libraries, we also need to ensure here all received ids are properly passed with the required `0x` prefix.

The method created here to prefix all the hex strings will later be used by dvote-js to do this same update in its internal eth interactions.

**Comment by jordipainan** [comment]
Related, but the method should be defined on the client, not on this repository that only has to do with smart-contracts
