### ISSUE TITLE
[sol] Split newProcess into two separate functions to save gas

### ISSUE THREAD

**Issue by brickpop** [vocdoni/dvote-solidity#3]
- [x] Adapt the contract
- [x] Split the wrappers for off-chain/evm censuses
- [x] Adapt the testing

**Comment by brickpop** [comment]
@jordipainan the intent of this issue is to have two entry points for creating processes. Now we have an entry point acting as a proxy of the 2 actual implementatios (EVM/Off-chain).

Saving one jump may save gas in the long run.

**Comment by jordipainan** [comment]
WIP: https://github.com/vocdoni/dvote-solidity/tree/feature/split-process-creation
